version: "3.9"
volumes:
  n8n_storage:

services:

#  # Kafka cluster
#  zookeeper:
#    hostname: zookeeper
#    container_name: zookeeper
#    image: confluentinc/cp-zookeeper:6.2.0
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#    ports:
#      - "2181:2181"
#    networks:
#      - chat-network
#  kafka-broker:
#    hostname: kafka-broker
#    container_name: kafka-broker
#    image: confluentinc/cp-kafka:6.2.0
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
#      KAFKA_LISTENERS: "PUBLIC://0.0.0.0:9092,INTERNAL://0.0.0.0:19092"
#      KAFKA_ADVERTISED_LISTENERS: "PUBLIC://kafka-broker:9092,INTERNAL://kafka-broker:19092"
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PUBLIC:PLAINTEXT,INTERNAL:PLAINTEXT"
#      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
#      KAFKA_NUM_PARTITIONS: 1
#      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
#      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_DELETE_TOPIC_ENABLE: "true"
#      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
#      KAFKA_LOG4J_ROOT_LOGLEVEL: "INFO"
#    depends_on:
#      - zookeeper
#    networks:
#      - chat-network
#  kafka-ui:
#    hostname: kafka-ui
#    container_name: kafka-ui
#    image: provectuslabs/kafka-ui:latest
#    ports:
#      - 8080:8080
#    depends_on:
#      - kafka-broker
#    environment:
#      DYNAMIC_CONFIG_ENABLED: 'true'
#      KAFKA_CLUSTERS_0_NAME: local-kafka
#      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-broker:9092
#    networks:
#      - chat-network

  # n8n:
  #   hostname: n8n
  #   container_name: n8n
  #   image: docker.n8n.io/n8nio/n8n
  #   restart: always
  #   ports:
  #     - 5678:5678
  #   volumes:
  #     - n8n_storage:/home/node/.n8n
  #   networks:
  #     - chat-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      REACT_APP_SUPABASE_URL: ${SUPABASE_URL}
      REACT_APP_SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
    depends_on:
      - backend
    networks:
      - chat-network

  # backend:
  #   build: ./backend
  #   ports:
  #     - "3001:3001"
  #   environment:
  #     SUPABASE_URL: ${SUPABASE_URL}
  #     SUPABASE_API_KEY: ${SUPABASE_API_KEY}
  #     N8N_WEBHOOK_URL: ${N8N_WEBHOOK_URL}
  #   networks:
  #     - chat-network

networks:
  chat-network:
    driver: bridge